/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SchoolDentalProgramRouteImport } from './routes/school-dental-program'
import { Route as MobileDentistJohannesburgRouteImport } from './routes/mobile-dentist-johannesburg'
import { Route as HomeVisitDentistRouteImport } from './routes/home-visit-dentist'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CorporateDentalWellnessRouteImport } from './routes/corporate-dental-wellness'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ServicesToothReplacementRouteImport } from './routes/services.tooth-replacement'
import { Route as ServicesTeethWhiteningRouteImport } from './routes/services.teeth-whitening'
import { Route as ServicesProfessionalToothCleaningRouteImport } from './routes/services.professional-tooth-cleaning'
import { Route as ServicesExtractionsRouteImport } from './routes/services.extractions'
import { Route as ServicesDenturesRouteImport } from './routes/services.dentures'
import { Route as ServicesBracesRouteImport } from './routes/services.braces'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolDentalProgramRoute = SchoolDentalProgramRouteImport.update({
  id: '/school-dental-program',
  path: '/school-dental-program',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileDentistJohannesburgRoute =
  MobileDentistJohannesburgRouteImport.update({
    id: '/mobile-dentist-johannesburg',
    path: '/mobile-dentist-johannesburg',
    getParentRoute: () => rootRouteImport,
  } as any)
const HomeVisitDentistRoute = HomeVisitDentistRouteImport.update({
  id: '/home-visit-dentist',
  path: '/home-visit-dentist',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateDentalWellnessRoute = CorporateDentalWellnessRouteImport.update({
  id: '/corporate-dental-wellness',
  path: '/corporate-dental-wellness',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const ServicesToothReplacementRoute =
  ServicesToothReplacementRouteImport.update({
    id: '/tooth-replacement',
    path: '/tooth-replacement',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesTeethWhiteningRoute = ServicesTeethWhiteningRouteImport.update({
  id: '/teeth-whitening',
  path: '/teeth-whitening',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesProfessionalToothCleaningRoute =
  ServicesProfessionalToothCleaningRouteImport.update({
    id: '/professional-tooth-cleaning',
    path: '/professional-tooth-cleaning',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesExtractionsRoute = ServicesExtractionsRouteImport.update({
  id: '/extractions',
  path: '/extractions',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesDenturesRoute = ServicesDenturesRouteImport.update({
  id: '/dentures',
  path: '/dentures',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesBracesRoute = ServicesBracesRouteImport.update({
  id: '/braces',
  path: '/braces',
  getParentRoute: () => ServicesRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/corporate-dental-wellness': typeof CorporateDentalWellnessRoute
  '/faq': typeof FaqRoute
  '/home-visit-dentist': typeof HomeVisitDentistRoute
  '/mobile-dentist-johannesburg': typeof MobileDentistJohannesburgRoute
  '/school-dental-program': typeof SchoolDentalProgramRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/braces': typeof ServicesBracesRoute
  '/services/dentures': typeof ServicesDenturesRoute
  '/services/extractions': typeof ServicesExtractionsRoute
  '/services/professional-tooth-cleaning': typeof ServicesProfessionalToothCleaningRoute
  '/services/teeth-whitening': typeof ServicesTeethWhiteningRoute
  '/services/tooth-replacement': typeof ServicesToothReplacementRoute
  '/blog/': typeof BlogIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/corporate-dental-wellness': typeof CorporateDentalWellnessRoute
  '/faq': typeof FaqRoute
  '/home-visit-dentist': typeof HomeVisitDentistRoute
  '/mobile-dentist-johannesburg': typeof MobileDentistJohannesburgRoute
  '/school-dental-program': typeof SchoolDentalProgramRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/braces': typeof ServicesBracesRoute
  '/services/dentures': typeof ServicesDenturesRoute
  '/services/extractions': typeof ServicesExtractionsRoute
  '/services/professional-tooth-cleaning': typeof ServicesProfessionalToothCleaningRoute
  '/services/teeth-whitening': typeof ServicesTeethWhiteningRoute
  '/services/tooth-replacement': typeof ServicesToothReplacementRoute
  '/blog': typeof BlogIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/corporate-dental-wellness': typeof CorporateDentalWellnessRoute
  '/faq': typeof FaqRoute
  '/home-visit-dentist': typeof HomeVisitDentistRoute
  '/mobile-dentist-johannesburg': typeof MobileDentistJohannesburgRoute
  '/school-dental-program': typeof SchoolDentalProgramRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/braces': typeof ServicesBracesRoute
  '/services/dentures': typeof ServicesDenturesRoute
  '/services/extractions': typeof ServicesExtractionsRoute
  '/services/professional-tooth-cleaning': typeof ServicesProfessionalToothCleaningRoute
  '/services/teeth-whitening': typeof ServicesTeethWhiteningRoute
  '/services/tooth-replacement': typeof ServicesToothReplacementRoute
  '/blog/': typeof BlogIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/corporate-dental-wellness'
    | '/faq'
    | '/home-visit-dentist'
    | '/mobile-dentist-johannesburg'
    | '/school-dental-program'
    | '/services'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/services/braces'
    | '/services/dentures'
    | '/services/extractions'
    | '/services/professional-tooth-cleaning'
    | '/services/teeth-whitening'
    | '/services/tooth-replacement'
    | '/blog/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/corporate-dental-wellness'
    | '/faq'
    | '/home-visit-dentist'
    | '/mobile-dentist-johannesburg'
    | '/school-dental-program'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/services/braces'
    | '/services/dentures'
    | '/services/extractions'
    | '/services/professional-tooth-cleaning'
    | '/services/teeth-whitening'
    | '/services/tooth-replacement'
    | '/blog'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/corporate-dental-wellness'
    | '/faq'
    | '/home-visit-dentist'
    | '/mobile-dentist-johannesburg'
    | '/school-dental-program'
    | '/services'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/services/braces'
    | '/services/dentures'
    | '/services/extractions'
    | '/services/professional-tooth-cleaning'
    | '/services/teeth-whitening'
    | '/services/tooth-replacement'
    | '/blog/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  CorporateDentalWellnessRoute: typeof CorporateDentalWellnessRoute
  FaqRoute: typeof FaqRoute
  HomeVisitDentistRoute: typeof HomeVisitDentistRoute
  MobileDentistJohannesburgRoute: typeof MobileDentistJohannesburgRoute
  SchoolDentalProgramRoute: typeof SchoolDentalProgramRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/school-dental-program': {
      id: '/school-dental-program'
      path: '/school-dental-program'
      fullPath: '/school-dental-program'
      preLoaderRoute: typeof SchoolDentalProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile-dentist-johannesburg': {
      id: '/mobile-dentist-johannesburg'
      path: '/mobile-dentist-johannesburg'
      fullPath: '/mobile-dentist-johannesburg'
      preLoaderRoute: typeof MobileDentistJohannesburgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-visit-dentist': {
      id: '/home-visit-dentist'
      path: '/home-visit-dentist'
      fullPath: '/home-visit-dentist'
      preLoaderRoute: typeof HomeVisitDentistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate-dental-wellness': {
      id: '/corporate-dental-wellness'
      path: '/corporate-dental-wellness'
      fullPath: '/corporate-dental-wellness'
      preLoaderRoute: typeof CorporateDentalWellnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/services/tooth-replacement': {
      id: '/services/tooth-replacement'
      path: '/tooth-replacement'
      fullPath: '/services/tooth-replacement'
      preLoaderRoute: typeof ServicesToothReplacementRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/teeth-whitening': {
      id: '/services/teeth-whitening'
      path: '/teeth-whitening'
      fullPath: '/services/teeth-whitening'
      preLoaderRoute: typeof ServicesTeethWhiteningRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/professional-tooth-cleaning': {
      id: '/services/professional-tooth-cleaning'
      path: '/professional-tooth-cleaning'
      fullPath: '/services/professional-tooth-cleaning'
      preLoaderRoute: typeof ServicesProfessionalToothCleaningRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/extractions': {
      id: '/services/extractions'
      path: '/extractions'
      fullPath: '/services/extractions'
      preLoaderRoute: typeof ServicesExtractionsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/dentures': {
      id: '/services/dentures'
      path: '/dentures'
      fullPath: '/services/dentures'
      preLoaderRoute: typeof ServicesDenturesRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/braces': {
      id: '/services/braces'
      path: '/braces'
      fullPath: '/services/braces'
      preLoaderRoute: typeof ServicesBracesRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface ServicesRouteChildren {
  ServicesBracesRoute: typeof ServicesBracesRoute
  ServicesDenturesRoute: typeof ServicesDenturesRoute
  ServicesExtractionsRoute: typeof ServicesExtractionsRoute
  ServicesProfessionalToothCleaningRoute: typeof ServicesProfessionalToothCleaningRoute
  ServicesTeethWhiteningRoute: typeof ServicesTeethWhiteningRoute
  ServicesToothReplacementRoute: typeof ServicesToothReplacementRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesBracesRoute: ServicesBracesRoute,
  ServicesDenturesRoute: ServicesDenturesRoute,
  ServicesExtractionsRoute: ServicesExtractionsRoute,
  ServicesProfessionalToothCleaningRoute:
    ServicesProfessionalToothCleaningRoute,
  ServicesTeethWhiteningRoute: ServicesTeethWhiteningRoute,
  ServicesToothReplacementRoute: ServicesToothReplacementRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  CorporateDentalWellnessRoute: CorporateDentalWellnessRoute,
  FaqRoute: FaqRoute,
  HomeVisitDentistRoute: HomeVisitDentistRoute,
  MobileDentistJohannesburgRoute: MobileDentistJohannesburgRoute,
  SchoolDentalProgramRoute: SchoolDentalProgramRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
